language: php


php:
  # 5.2 error: Parse error: syntax error, unexpected T_START_HEREDOC in
  # /home/travis/build/klenwell/WikkaWiki/handlers/show.php on line 40
  #- 5.2
  - 5.3
  - 5.4
  - 5.5
  
before_script:
  - cp test/travis-ci.config.php-dist test/test.config.php

script: phpunit --stderr test
