<?php
#
# Default Pages
# List of pages created on initial install (source is located in lang dir)
#
$WikkaInstallDefaultPages = array(
    '_rootpage', 
    'AdminBadWords',
    'AdminPages',
    'AdminSpamLog',
    'AdminUsers',
    'CategoryAdmin',
    'CategoryCategory', 
    'CategoryWiki', 
    'DatabaseInfo',
    'FormattingRules', 
    'HighScores', 
    'InterWiki', 
    'MyChanges', 
    'MyPages', 
    'OrphanedPages', 
    'OwnedPages', 
    'PageIndex', 
    'PasswordForgotten', 
    'RecentChanges', 
    'RecentComments',
    'RecentlyCommented', 
    'SandBox', 
    'SysInfo',
    'TableMarkup',
    'TableMarkupReference',
    'TextSearch', 
    'TextSearchExpanded', 
    'UserSettings', 
    'WantedPages', 
    'WikiCategory', 
    'WikkaConfig', 
    'WikkaDocumentation', 
    'WikkaMenulets',
    'WikkaReleaseNotes'
);
